export const SEARCH_ROBOTS = "SEARCH_ROBOTS"
export const UPDATE_ROBOTS_PENDING = "UPDATE_ROBOTS_PENDING"
export const UPDATE_ROBOTS_SUCCESS = "UPDATE_ROBOTS_SUCCESS"
export const UPDATE_ROBOTS_FAILURE = "UPDATE_ROBOTS_FAILURE"
